// Toyota Camry data generated on 3/15/2025
const carData = [
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2018,
    "mileage": 67918,
    "price": 14079,
    "condition": "Fair",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Red",
    "vin": "4T1BF1FKI6955736",
    "location": "Philadelphia, PA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2018,
    "mileage": 77290,
    "price": 14628,
    "condition": "Fair",
    "fuel_type": "Gasoline",
    "transmission": "Manual",
    "color": "Red",
    "vin": "4T1BF1FKI3023622",
    "location": "San Jose, CA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Wireless Charging"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2018,
    "mileage": 60254,
    "price": 15732,
    "condition": "Fair",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Silver",
    "vin": "4T1BF1FKI9673710",
    "location": "Phoenix, AZ",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2019,
    "mileage": 53170,
    "price": 17824,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Green",
    "vin": "4T1BF1FKJ0098218",
    "location": "New York, NY",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2019,
    "mileage": 72949,
    "price": 15846,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Silver",
    "vin": "4T1BF1FKJ5705118",
    "location": "San Antonio, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2019,
    "mileage": 69049,
    "price": 17833,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Blue",
    "vin": "4T1BF1FKJ1500302",
    "location": "Philadelphia, PA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2020,
    "mileage": 49316,
    "price": 17899,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Gray",
    "vin": "4T1BF1FKK6535087",
    "location": "Chicago, IL",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2020,
    "mileage": 36680,
    "price": 19331,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Green",
    "vin": "4T1BF1FKK2456606",
    "location": "Dallas, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2020,
    "mileage": 33924,
    "price": 19239,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "White",
    "vin": "4T1BF1FKK4881000",
    "location": "San Diego, CA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Ventilated Seats"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2021,
    "mileage": 40178,
    "price": 18904,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Green",
    "vin": "4T1BF1FKL3907383",
    "location": "San Diego, CA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Ventilated Seats"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2021,
    "mileage": 30518,
    "price": 17926,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "Manual",
    "color": "Gray",
    "vin": "4T1BF1FKL7737297",
    "location": "Dallas, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2021,
    "mileage": 39156,
    "price": 20031,
    "condition": "Good",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Green",
    "vin": "4T1BF1FKL5451287",
    "location": "Houston, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2022,
    "mileage": 20445,
    "price": 19484,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "Manual",
    "color": "Blue",
    "vin": "4T1BF1FKM4334433",
    "location": "Dallas, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2022,
    "mileage": 23648,
    "price": 19578,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Blue",
    "vin": "4T1BF1FKM1863996",
    "location": "Philadelphia, PA",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Premium Sound System"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2022,
    "mileage": 20348,
    "price": 22596,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Gray",
    "vin": "4T1BF1FKM1589525",
    "location": "Houston, TX",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2023,
    "mileage": 10200,
    "price": 22039,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "CVT",
    "color": "Green",
    "vin": "4T1BF1FKN7913207",
    "location": "Phoenix, AZ",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Premium Sound System"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2023,
    "mileage": 12985,
    "price": 23855,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "Manual",
    "color": "Blue",
    "vin": "4T1BF1FKN3494836",
    "location": "New York, NY",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  },
  {
    "id": 2469,
    "make": "Toyota",
    "model": "Camry LE",
    "year": 2023,
    "mileage": 12032,
    "price": 24273,
    "condition": "Excellent",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "color": "Green",
    "vin": "4T1BF1FKN0369668",
    "location": "New York, NY",
    "features": [
      "Bluetooth",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control"
    ],
    "nhtsa_id": 2469,
    "nhtsa_name": "Camry"
  }
];